# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'KSVSSdkApiDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'KSYMediaEditorKit', '2.2.3'
    pod 'Ks3SDK','1.7.2'
    pod 'Bugly'
    pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'YYKit'
    pod 'UICKeyChainStore'
    pod 'FMDB'
    pod 'AFNetworking', '~> 3.0'
    pod 'Toast', '~> 4.0.0'

  # Pods for KSVSSdkApiDemo

end
